spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true

#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.ddl-auto=${DDL:create-drop}
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.hibernate.ddl-auto=create


spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.platform=postgress
spring.datasource.url=jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:estacionamento}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

server.port=8080
